VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IAccount"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Account VB6 example #3
' Copyright ©2002 by Desaware Inc.  All Rights Reserved
Option Explicit

Public Sub Deposit(ByVal Amount As Currency)
End Sub

Public Sub Withdraw(ByVal Amount As Currency)
End Sub

Public Function ChargeAccount() As Currency
End Function

